[build]
  publish = "client/dist"
  command = "npm install drizzle-zod --force && npm run build && npm run db:push"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
