[build]
  publish = "client/dist"
  command = "DATABASE_URL='postgresql://neondb_owner:npg_bJtUQiu7XKh3@ep-restless-mode-a50f826j-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require' npm run build && DATABASE_URL='postgresql://neondb_owner:npg_bJtUQiu7XKh3@ep-restless-mode-a50f826j-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require' npm run db:push"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
