[build]
  publish = "client/dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5000
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
